stages:
  load_data:
    cmd: python src/load_data.py ${data.filepath} ${data.processed}train_test_data.csv
    deps:
      - src/load_data.py
      - ${data.filepath}
    outs:
      - ${data.processed}train_test_data.csv

  preprocess:
    cmd: python src/preprocess_data.py ${data.processed}train_test_data.csv ${data.processed}X_train.csv ${data.processed}X_test.csv ${data.processed}y_train.csv ${data.processed}y_test.csv
    deps:
      - src/preprocess_data.py
      - ${data.processed}train_test_data.csv
    outs:
      - ${data.processed}X_train.csv
      - ${data.processed}X_test.csv
      - ${data.processed}y_train.csv
      - ${data.processed}y_test.csv

  train_logistic:
    cmd: python src/train.py data/processed/X_train.csv data/processed/y_train.csv logistic_regression
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/logistic_regression_model.pkl

  train_random_forest:
    cmd: python src/train.py data/processed/X_train.csv data/processed/y_train.csv random_forest
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/random_forest_model.pkl

  evaluate_logistic:
    cmd: python src/evaluate.py models/logistic_regression_model.pkl data/processed/X_test.csv data/processed/y_test.csv reports/logistic_evaluation.txt runids/logistic_regression.txt
    deps:
      - src/evaluate.py
      - models/logistic_regression_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/logistic_evaluation.txt


  evaluate_random_forest:
    cmd: python src/evaluate.py models/random_forest_model.pkl data/processed/X_test.csv data/processed/y_test.csv reports/random_forest_evaluation.txt runids/random_forest.txt
    deps:
      - src/evaluate.py
      - models/random_forest_model.pkl
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/random_forest_evaluation.txt
