data:
  filepath: "./data/raw/ai4i2020.csv"
  processed: ./data/processed/
  models: ./models/

run:
  filepath: "./runids/"

models:
  logistic_regression:
    max_iter: 1000
    C: 1.0
    random_state: 42
    fit_intercept: true
  random_forest:
    n_estimators: 100
    max_depth: 2
    random_state: 42


mlflow:
  experiment_name: "Predictive Maintenance Analysis"
  tracking_uri: "http://127.0.0.1:5000"
  tags:
    data_version: "v1.0"
    author: "Equipo 30"
    description: "Modelo para predecir cuando una maquina necesita mantenimiento"